name: branvier_lints
description: Lints used in Branvier projects.
version: 0.10.0
homepage: https://github.com/branvier-dev/branvier_lints
topics: [branvier, lints, linter, analysis, analyzer]

environment:
  sdk: '>=3.10.0 <4.0.0'

